baseURL = 'https://book-ebx.pages.dev/'
locale = 'zh-cn'
title = '西流未央的博客'
theme = 'PaperMod'

[params]
  description = "When a man cannot choose, he ceases to be a man"
  favicon = "/favicon.ico"
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  TocOpen = false

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
