baseURL = 'https://book-ebx.pages.dev/'
locale = 'zh-cn'
title = '西流未央的博客'
theme = 'PaperMod'

[params]
  description = "When a man cannot choose, he ceases to be a man"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  TocOpen = false
  mainSections = ["社会观察", "精神自省"]

[params.assets]
  favicon = "/favicon.png"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
