baseURL = 'https://book-ebx.pages.dev/'
locale = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '西流未央的博客'
theme = 'PaperMod'

[params]
  author = "西流未央"
  description = "When a man cannot choose, he ceases to be a man"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  mainSections = ["社会观察", "精神自省"]

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"

  [params.label]
    text = "西流未央的博客"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:sunmonglin@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
